apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: library-management-db
  name: library-management-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: library-management-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: library-management-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: library_management_db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: user
          image: postgres:15
          name: library-management-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: library-management-data
      restartPolicy: Always
      volumes:
        - name: library-management-data
          persistentVolumeClaim:
            claimName: library-management-data
